### ISSUE TITLE
Point in time resets to ”now”

### ISSUE THREAD

**Issue by perpatrik79** [JohanBendz/se.swefa#10]
**Describe the bug**

Trying to set ”point in time” for weather-forecast at eight hours. It works when setting it up. When I reopen the Homey-app a couple of hours later, the forecast shows point in time=now. This despite point in time settings still equals eight hours. I am running Homey firmware 5.0.

**Comment by JohanBendz** [comment]
Hi @perpatrik79, new version in app store. Can you please see if this fix your problem?

**Comment by perpatrik79** [comment]
Seems like it works now. Thank you!

tors 26 nov. 2020 kl. 11:52 skrev Johan Bendz <notifications@github.com>:
