### ISSUE TITLE
Weather forecast not updating automatically

### ISSUE THREAD

**Issue by dybedal** [JohanBendz/se.swefa#11]
**Describe the bug**
Forecast does not update automatically. This was working until recently, so I suspect that the issue was introduced in the latest update.

**To Reproduce**
1. Create a Weather device in Homey
2. Select forecast "Now"
3. Set "Use Homey GEOlocation" to "Yes"

**Expected behavior**
The weather data should update once every hour with the current forecast for the selected location.

**Actual behavior**
The weather data never updates automatically. An update can be "forced" by entering manual GEOlocation, and setting "Use Homey GEOlocation" to "No". This will update the weather data *once*.

**Homey (please complete the following information):**
 - Homey OS: 5.0.0
 - Mobile App: 6.3.1.672
 - Installed from: App store
 - Version of the App: v0.4.5

**Crash report ID**
I have submitted a crash report from the app with the following ID:

`7e09624c-623a-4a18-8fb2-83dd43733769`

**Comment by JohanBendz** [comment]
Hi @dybedal, the issue is related to too many decimals in your longitude. SMHI responds with an error when your 7 digit decimal longitude is sent to them. I will implement a 6 digit limit. Sorry for the inconvenience and thanks for reporting!

**Comment by dybedal** [comment]
Hi @JohanBendz! As far as I can see I am only using 6 decimals (8.091910).

Also, when "Use Homey GEOlocation" is set to "Yes", it is still not working (and I don't know how many decimals Homey is using).

As mentioned, I can get it to update successfully by toggling Homey GEOloaction to "No". But it will only update once and I have to toggle "No"->"Yes"->"No" to get it to update again.

I sent a new diagnostic report after "forcing" the update this way.

`5cfd9e83-48f3-4105-9c23-2a2956785455`

**Comment by JohanBendz** [comment]
Hi @dybedal, can you please try this version: https://homey.app/a/se.swefa/test/
Let me know if it works for you.

**Comment by dybedal** [comment]
Looks like it's working! Thanks a lot for your quick response!
