### ISSUE TITLE
Rain or snow condition card not working

### ISSUE THREAD

**Issue by asteman** [JohanBendz/se.swefa#4]
**Describe the bug**
I believe the condition card for Rain or snow is still broken.

**To Reproduce**
Made quick test with a logic card that "contains". It triggers, but not SMHI one.

![image](https://user-images.githubusercontent.com/25367091/59249489-30af8a80-8c25-11e9-93bf-8965270fd139.png)

**Expected behavior**

**Screenshots**

**Homey (please complete the following information):**
 - Homey OS: 2.1.2
 - Mobile App: 2.4.0.328
 - Installed from App store
 - Version of the App 0.3.7

**Comment by rindlerblabla** [comment]
Same with Low cloud cover. The internal AND-condition is not working, but the Logic card is.

**Comment by JohanBendz** [comment]
Thanks @asteman, I have now identified and solved the issue.
Thanks @rindlerblabla, I can replicate the issue but I have not found the bug yet.. troubleshooting that one.

New Alpha version on it's way asap.

**Comment by fjeldstad** [comment]
@JohanBendz I've experienced the same with the "precipitation situtation change" trigger. Maybe it's related?

This flow never triggers:
![image](https://user-images.githubusercontent.com/905731/62778312-5daadd00-bab0-11e9-9259-4cf4158ae88a.png)

**Comment by JohanBendz** [comment]
Thanks everyone for your feedback, a new Beta version is now out that should solve this issue.

// Johan
